import argparse
import sys
import arcade
from pydantic import ValidationError
from src.maze_app.parsing.config_parser import parse_config
from src.maze_app.parsing.models import MazeConfig
from src.maze_app.output.export import export_to_file
from src.mazegen import MazeGenerator
from src.maze_app.exceptions import MazeGenerationError
from src.maze_app.display.arcade_visualizer import ArcadeVisualizer
from src.maze_app.display.ascii_visualizer import AsciiVisualizer
from debug_utils import print_italic, print_green, debug_draw_maze


def main(config_path: str) -> None:
    # Extract a configuration from the `config_path` file
    print_italic(f"\nReading the configuration file: {config_path}...")
    try:
        config_parsed = parse_config(config_path)
        print_green("__DEBUG__ Loaded configuration:")
        for key, value in config_parsed.items():
            print_green(f"'{key}'", ':')
            print_green(f"'{value}'")

    except (FileNotFoundError, PermissionError) as err:
        print(f"Error: the file '{config_path}' can't be accessed\n {err}",
              file=sys.stderr)
        sys.exit(1)
    except ValueError as err:
        print(f"Error: bad syntax in the configuration file: {err}",
              file=sys.stderr)
        sys.exit(1)
    except Exception as err:
        print(f"Unexpected error during parsing: {err}", file=sys.stderr)
        sys.exit(1)

    # Validate config extracted from file and instance data model with Pydantic
    print_italic("\nValidating data configuration...")
    try:
        config = MazeConfig(**config_parsed)
        print_green(f"__DEBUG__\n{config.model_dump_json(indent=4)}")

    except ValidationError as err:
        print("Error validating maze parameters:", file=sys.stderr)
        # err.errors() returns a list of all errors, as dictionaries
        # each dict looks like {'type': 'equal', 'loc': ('a_var',), 'msg': ...
        for error in err.errors():
            # loc is a tuple that specifies exactly WHERE the error occurred
            # if no `loc` key, .get() returns an empty tuple ()
            loc = error.get('loc', ())
            # if error comes from model's consistency (not a specific field),
            # Pydantic often returns an empty or generic loc :
            # `Global` indicate a cross-validation rule has failed
            field_name = loc[0] if loc else "Global"
            # Extract raw error message, generated by Pydantic or by a `raise`
            raw_msg = error.get('msg', '')

            # Message cleanup: spaces and redundant Pydantic préfix Value error
            cleaned_msg = raw_msg.replace('Value error,', '').strip()
            print(f"  - [{field_name}] : {cleaned_msg}", file=sys.stderr)
        sys.exit(1)

    # `config` object is validated, typed, and ready for use
    print_italic("Config successfully validated! ")

    # -------------------- TODO ---------------------------------
    # --- GÉNÉRER LE LABYRINTHE AVEC LA CONFIG VALIDÉE ---

    # INSTANCIE le labyrinthe selon la config
    print_italic("\nGenerating the maze...")
    try:
        maze = MazeGenerator(
            width=config.width,
            height=config.height,
            seed=config.seed,
            entry_coord=config.entry_coord,
            exit_coord=config.exit_coord
        )
    except ValueError as err:
        print(f"Error: Can't instantiate the maze, {err}", file=sys.stderr)
        sys.exit(1)

    # GENERE le labyrinthe
    maze.generate_perfect_maze()

    if not config.perfect:
        print_italic("Setting the maze to imperfect...")
        try:
            maze.make_imperfect()
        except RuntimeError as err:
            print(f"Error: maze must be firstly generated, {err}",
                  file=sys.stderr)
            sys.exit(1)

    # VALIDE le labyrinthe
    # if mandatory rules not followed -> throw an exception
    if not maze.check_walls_integrity() or not maze.check_no_large_areas():
        raise MazeGenerationError("Generated maze does not comply with rules.")

    print_italic("\nThe maze is compliant with mandatory rules")

    # -------------------- TODO ---------------------------------
    # --- AFFICHER LE LABYRINTHE
    if config.display_mode == "ascii":
        visualizer = AsciiVisualizer(maze)
        visualizer.update()
    elif config.display_mode == "arcade":
        window = arcade.Window(1280, 720,
                            "A-Maze-Ing",
                            fullscreen=False)
        visualizer = ArcadeVisualizer(maze)
        window.show_view(visualizer)
        arcade.run()

    # -------------------- TODO ---------------------------------
    # --- TROUVER LE CHEMIN LE PLUS COURT
    try:
        shortest_path: str = maze.solve_maze()
        print(shortest_path)
    except RuntimeError as err:
        print(f"Error: maze must be firstly generated, {err}",
              file=sys.stderr)
        sys.exit(1)

    # -------------------- TODO ---------------------------------
    # --- EXPORTER le labyrinthe et la solution dans un fichier texte
    # if not done yet, first solve: `shortest_path: str = maze.solve_maze()`
    export_to_file(maze.grid, maze.entry_coord, maze.exit_coord, shortest_path,
                   config.output_file)


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Mazegen execution script")
    parser.add_argument("config_path", type=str,
                        help="Path to the maze configuration file")

    args = parser.parse_args()
    main(args.config_path)
