[project]
name = "mazegen"
version = "0.1.0"
description = "A_Maze_ing project"
readme = "README.md"
requires-python = ">=3.10"


# mazegen n'a besoin de rien d'externe
dependencies = []

[dependency-groups]
dev = [
    "flake8>=7.3.0",
    "mypy>=2.1.0",
    "pytest>=9.1.1",
]
app = [
    "arcade>=3.3.3",
    "colorama>=0.4.6",
    "pydantic>=2.13.4",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

# pour le .whl uniquement
[tool.hatch.build.targets.wheel]
# empaqueter UNIQUEMENT ce fichier
include = ["src/mazegen.py"]
[tool.hatch.build.targets.wheel.sources]
# "rebaser" le contenu de `src/` vers la racine du wheel
"src" = ""

# pour le .tar.gz
[tool.hatch.build.targets.sdist]
include = [
    "src/mazegen.py",
    "pyproject.toml", # ce fichier dit à `pip`/`build` avec quel outil et comment construire le package
    "README.md",      # référencé explicitement dans les métadonnées, son contenu sera la description longue du package
    "LICENSE.md",     # bonne pratique, la licence doit accompagner un module réutilisable et redistribuable
]

[tool.mypy]
# exclure explicitement venv & Cie
exclude = ["^\\.venv/", "^build/", "^dist/"]

# Règles strictes de typage (extraites du Makefile, pour qu'il soit + lisible)
warn_return_any = true
warn_unused_ignores = true
ignore_missing_imports = true
disallow_untyped_defs = true
check_untyped_defs = true

# pour améliorer la capacité de mypy à vérifier le code spécifiques à pydantic
plugins = ["pydantic.mypy"]

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true

# avant sa collecte des tests, pytest ajoutera '.' (racine du projet) à sys.path
[tool.pytest.ini_options]
pythonpath = ["."]